name: yumm_yum
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  random_string: ^2.3.1
  shared_preferences: ^2.1.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  flutter_stripe: ^11.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
